# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - '**/*.erb'
    - 'config/application.rb'
    - 'config/environment.rb'
    - 'config/environments/production.rb'
    - 'config/environments/test.rb'
    - 'config/initializers/filter_parameter_logging.rb'
    - 'config/initializers/new_framework_defaults_7_1.rb'
    - 'db/migrate/20231115012150_add_service_name_to_active_storage_blobs.active_storage.rb'
    - 'db/migrate/20231115012151_create_active_storage_variant_records.active_storage.rb'
    - 'db/migrate/20231115012152_remove_not_null_on_active_storage_blobs_checksum.active_storage.rb'
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - '**/*_spec.rb'
