# Name of your application. Used to uniquely configure containers.
service: tank-share

# Name of the container image.
image: user/my-app

# Deploy to these servers.
servers:
  web:
    - MRSK_DEPLOY_IP_1

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: MRSK_REGISTRY_USERNAME

  # Always use an access token rather than real password when possible.
  password:
    - MRSK_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
env:
  clear:
    DB_HOST: MRSK_DB_HOST
  secret:
    - RAILS_MASTER_KEY
    - MRSK_POSTGRES_PASSWORD

accessories:
  db:
    image: postgres:15
    host: MRSK_POSTGRES_HOST
    port: MRSK_POSTGRES_PORT
    env:
      clear:
        POSTGRES_USER: MRSK_POSTGRES_USER
        POSTGRES_DB: MRSK_POSTGRES_DB
      secret:
        - MYSQL_ROOT_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    host: MRSK_DEPLOY_IP_1
    port: 6379
    directories:
      - data:/data
