# Name of your application. Used to uniquely configure containers.
service: tank_share

<% require "dotenv"; Dotenv.load(".env") %>

# Name of the container image.
image: albertski/tank_share

# Deploy to these servers.
servers:
  web:
    - <%= ENV['KAMAL_SERVER'] %>
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# If using something like Cloudflare, it is recommended to set encryption mode
# in Cloudflare's SSL/TLS setting to "Full" to enable end-to-end encryption.
proxy:
  ssl: true
  host: tankshare.net
  app_port: 80
  healthcheck:
    path: /up
    interval: 7
    timeout: 49

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username:
    - KAMAL_REGISTRY_USERNAME

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  secrets:
    - KAMAL_REGISTRY_USERNAME
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
#
env:
  clear:
    DB_HOST: KAMAL_SERVER
  secret:
    - RAILS_LOG_LEVEL
    - RAILS_MASTER_KEY
    - KAMAL_REGISTRY_PASSWORD
    - KAMAL_REGISTRY_USERNAME
    - POSTGRES_USER
    - POSTGRES_DB
    - POSTGRES_PASSWORD
    - POSTGRES_HOST
    - REDIS_URL

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
#
aliases:
  console: app exec -r -i "bundle exec rails console"
  shell: app exec -i bash
  logs: app logs -f

# Use a different ssh user than root
#
# ssh:
#   user: app

# Use a persistent storage volume.
#
# volumes:
#   - "app_storage:/app/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
asset_path: /rails/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
#
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Use accessory services (secrets come from .kamal/secrets).
#
